[phases.setup]
nixPkgs = ["maven", "jdk17"]

[phases.build]
cmds = ["cd backend && mvn clean package -DskipTests"]

[phases.start]
cmd = "cd backend && java -jar target/sales-lead-system-0.0.1-SNAPSHOT.jar"
